name: Question
description: API の使い方に関する質問
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        まず [API ドキュメント](https://docs.ppn-hub.com) をご確認ください。

  - type: input
    id: api
    attributes:
      label: API Name
      description: 対象の API 名
      placeholder: "address"
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Question
      description: 質問内容を具体的に記述してください
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: What have you tried?
      description: 既に試したことがあれば記述してください
    validations:
      required: false
